spring:
  application:
    name: ttimpex
  datasource:
    url: jdbc:postgresql://localhost:5432/timestamp?currentSchema=timestamp
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
#  jackson:
#    serialization:
#      write-dates-as-timestamps: false

server:
  port: 8089

app:
  path-db: C:\TREZOR2\DATA
  sleep: 6000
  night: 9000
  time:
    start: 7
    end: 20

