spring:
  application:
    name: ttimpex
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: timestamp
    defer-datasource-initialization: true
  #  jackson:
#    serialization:
#      write-dates-as-timestamps: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port: ${PORT:8080}

app:
  path-db: C:\TREZOR2\DATA
  sleep: 6000
  night: 9000
  time:
    start: 7
    end: 20

springdoc:
  api-docs:
    path: /api-docs

